import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}

        {/* Bottom NavBar */}
        <div className="fixed bottom-0 left-0 right-0 bg-gray-800 p-4 grid grid-cols-4 text-center">

          {/* Home Button */}
          <Link href="/">
            <button className="text-white hover:text-gray-400 focus:outline-none">
              <span className="text-lg">Home</span>
            </button>
          </Link>

          {/* Login Button */}
          <Link href="/login">
            <button className="text-white hover:text-gray-400 focus:outline-none">
              <span className="text-lg">Login</span>
            </button>
          </Link>

          {/* User Button */}
          <Link href="/user">
            <button className="text-white hover:text-gray-400 focus:outline-none">
              <span className="text-lg">User</span>
            </button>
          </Link>

          {/* Logout Button */}
          <Link href="/logout">
            <button className="text-white hover:text-gray-400 focus:outline-none">
              <span className="text-lg">Logout</span>
            </button>
          </Link>
        </div>

      </body>
    </html>
  )
}
